# Generated by Django 3.2.3 on 2021-05-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sate',
            new_name='state',
        ),
    ]
